spring:
  application:
    name: snap-nephalem-shuang
server:
  port: 8088
logging:
  level:
    com:
      haoait:
        client:
          UserServiceClient: debug
netty:
  server-socket:
    url: 127.0.0.1